Repository WildCodeSchool-2024-02/JS-lyon-0224-P3-cretchum, pull requests merged in 2024-06, with the labels that each got.

#3 add police font family, colors in root, reset css and background-color
  client/src/App.css
  client/src/assets/fonts/roboto/LICENSE.txt
  client/src/assets/fonts/roboto/Roboto-Black.ttf
  client/src/assets/fonts/roboto/Roboto-BlackItalic.ttf
  client/src/assets/fonts/roboto/Roboto-Bold.ttf
  client/src/assets/fonts/roboto/Roboto-BoldItalic.ttf
  client/src/assets/fonts/roboto/Roboto-Italic.ttf
  client/src/assets/fonts/roboto/Roboto-Light.ttf
  client/src/assets/fonts/roboto/Roboto-LightItalic.ttf
  client/src/assets/fonts/roboto/Roboto-Medium.ttf
  client/src/assets/fonts/roboto/Roboto-MediumItalic.ttf
  client/src/assets/fonts/roboto/Roboto-Regular.ttf
  client/src/assets/fonts/roboto/Roboto-Thin.ttf
  client/src/assets/fonts/roboto/Roboto-ThinItalic.ttf
Labels: REVIEWED

#6 Us 13 Home page
  client/src/assets/logo/1patounes.png
  client/src/assets/logo/cicorne.png
  client/src/components/home_page/HomePage.jsx
  client/src/components/home_page/homePage-style.css
Labels: REVIEW REQUESTED

#7 03 user form
  client/src/App.css
  client/src/assets/images/2patounes.png
  client/src/main.jsx
  client/src/pages/signin/SignIn.jsx
  client/src/pages/signin/SignIn.module.css
Labels: REVIEW REQUESTED

#11 01 search page
  client/src/App.css
  client/src/assets/images/cat.png
  client/src/assets/images/dog.png
  client/src/assets/images/person.jpg
  client/src/components/SearchPage/Filter.css
  client/src/components/SearchPage/Filter.jsx
  client/src/components/SearchPage/HomeStructureList.css
  client/src/components/SearchPage/HomeStructureList.jsx
  client/src/main.jsx
  client/src/pages/SearchPage.css
  client/src/pages/SearchPage.jsx
Labels: REVIEW REQUESTED

#13 02_database
  server/database/fixtures/HomeStructureSeeder.js
  server/database/fixtures/UserSeeder.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#9 16_navigation_menu
  client/src/App.jsx
  client/src/pages/NavMenu.css
  client/src/pages/NavMenu.jsx
Labels: REVIEW REQUESTED

#18 Fix 01
  client/src/App.css
  client/src/pages/NavMenu.css
  client/src/pages/signin/SignIn.jsx
  client/src/pages/signin/SignIn.module.css
Labels: REVIEW REQUESTED

#19 24 components connexion
  client/src/App.jsx
  client/src/components/nav_menu/NavMenu.css
  client/src/components/nav_menu/NavMenu.jsx
  client/src/main.jsx
  client/src/pages/home_page/HomePage.jsx
  client/src/pages/home_page/homePage.css
  client/src/pages/search-page/SearchPage.css
  client/src/pages/search-page/SearchPage.jsx
  client/src/pages/signin/SignIn.jsx
Labels: REVIEW REQUESTED

#22 modification name import images and remove maxlength passewords and …
  client/src/components/SearchPage/HomeStructureList.jsx
  client/src/pages/home_page/HomePage.jsx
  client/src/pages/search-page/SearchPage.jsx
  client/src/pages/signin/SignIn.jsx
Labels: REVIEW REQUESTED

#23 modification remove maxlength passewords and modification maxlength …
  client/src/pages/signin/SignIn.jsx
Labels: REVIEW REQUESTED

#21 Sprint 1
  client/index.html
  client/src/App.css
  client/src/App.jsx
  client/src/assets/fonts/roboto/LICENSE.txt
  client/src/assets/fonts/roboto/Roboto-Black.ttf
  client/src/assets/fonts/roboto/Roboto-BlackItalic.ttf
  client/src/assets/fonts/roboto/Roboto-Bold.ttf
  client/src/assets/fonts/roboto/Roboto-BoldItalic.ttf
  client/src/assets/fonts/roboto/Roboto-Italic.ttf
  client/src/assets/fonts/roboto/Roboto-Light.ttf
  client/src/assets/fonts/roboto/Roboto-LightItalic.ttf
  client/src/assets/fonts/roboto/Roboto-Medium.ttf
  client/src/assets/fonts/roboto/Roboto-MediumItalic.ttf
  client/src/assets/fonts/roboto/Roboto-Regular.ttf
  client/src/assets/fonts/roboto/Roboto-Thin.ttf
  client/src/assets/fonts/roboto/Roboto-ThinItalic.ttf
  client/src/assets/images/2patounes.png
  client/src/assets/images/cat.png
  client/src/assets/images/dog.png
  client/src/assets/images/person.jpg
  client/src/assets/logo/1patounes.png
  client/src/assets/logo/cicorne.png
  client/src/components/SearchPage/Filter.css
  client/src/components/SearchPage/Filter.jsx
  client/src/components/SearchPage/HomeStructureList.css
  client/src/components/SearchPage/HomeStructureList.jsx
  client/src/components/nav_menu/NavMenu.css
  client/src/components/nav_menu/NavMenu.jsx
  client/src/main.jsx
  client/src/pages/home_page/HomePage.jsx
  client/src/pages/home_page/homePage.css
  client/src/pages/search-page/SearchPage.css
  client/src/pages/search-page/SearchPage.jsx
  client/src/pages/signin/SignIn.jsx
  client/src/pages/signin/SignIn.module.css
  package-lock.json
  server/app/config.js
  server/app/controllers/itemActions.js
  server/app/routers/api/items/router.js
  server/app/routers/api/router.js
  server/database/fixtures/HomeStructureSeeder.js
  server/database/fixtures/ItemSeeder.js
  server/database/fixtures/UserSeeder.js
  server/database/models/ItemRepository.js
  server/database/schema.sql
  server/database/tables.js
  server/package.json
Labels: REVIEW REQUESTED

#26 25 back routes
  server/app/controllers/home_structureActions.js
  server/app/controllers/usersActions.js
  server/app/routers/api/home_structure/router.js
  server/app/routers/api/router.js
  server/app/routers/api/users/router.js
  server/database/fixtures/HomeStructureSeeder.js
  server/database/models/HomeStructureRepository.js
  server/database/models/UsersRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEW REQUESTED

#30 27 link sign in form to bdd
  client/src/main.jsx
  client/src/pages/signin/SignIn.jsx
  package-lock.json
  server/app/controllers/usersActions.js
  server/app/routers/api/users/router.js
  server/app/services/validateSignIn.js
  server/database/fixtures/UserSeeder.js
  server/database/models/UsersRepository.js
  server/database/schema.sql
  server/package.json
Labels: REVIEW REQUESTED

#31 30 filter search page
  client/src/components/SearchPage/Filter.css
  client/src/components/SearchPage/Filter.jsx
  client/src/pages/search-page/SearchPage.jsx
Labels: REVIEW REQUESTED

#33 26_connexion_page
  client/src/main.jsx
  client/src/pages/Connexion_page/ConnexionPage.css
  client/src/pages/Connexion_page/ConnexionPage.jsx
  server/app/controllers/usersActions.js
  server/app/routers/api/users/router.js
  server/app/services/ValidateLogin.js
  server/database/models/UsersRepository.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#35 Fix sprint2
  client/src/App.css
  client/src/components/SearchPage/Filter.jsx
  client/src/components/nav_menu/NavMenu.css
  client/src/pages/Connexion_page/ConnexionPage.css
  client/src/pages/home_page/HomePage.jsx
  client/src/pages/home_page/homePage.css
  client/src/pages/signin/SignIn.jsx
  client/src/pages/signin/SignIn.module.css
  server/app/services/validateSignIn.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#37 Fix sprint2
  client/src/components/SearchPage/Filter.css
  client/src/components/SearchPage/Filter.jsx
Labels: REVIEW REQUESTED

#36 04 form home structure
  client/src/main.jsx
  client/src/pages/home_page/HomePage.jsx
  client/src/pages/home_page/homePage.css
  client/src/pages/structure_form/StructureForm.jsx
  client/src/pages/structure_form/StructureForm.module.css
Labels: REVIEW REQUESTED

#39 Sprint2 fix
  client/.env.sample
  client/src/components/SearchPage/Filter.jsx
  client/src/main.jsx
  client/src/pages/search-page/SearchPage.jsx
  client/src/pages/signin/SignIn.module.css
  server/app/services/ValidateLogin.js
  server/app/services/validateSignIn.js
Labels: REVIEW REQUESTED

#42 31 order by capacity
  server/database/fixtures/HomeStructureSeeder.js
  server/database/models/HomeStructureRepository.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#46 06 profile page
  client/src/App.css
  client/src/assets/images/penblue.png
  client/src/components/profile/EditableField.jsx
  client/src/components/profile/EditableField.module.css
  client/src/components/profile/ProfileHeader.jsx
  client/src/components/profile/ProfileHeader.module.css
  client/src/components/profile/ProfileSection.jsx
  client/src/components/profile/ProfileSection.module.css
  client/src/main.jsx
  client/src/pages/profile_page/ProfilePage.jsx
  client/src/pages/profile_page/ProfilePage.module.css
Labels: CORRECTIONS DONE, REVIEW REQUESTED

#47 19 search bar
  client/src/assets/images/Btn-next.png
  client/src/assets/images/Btn-prev.png
  client/src/components/SearchPage/Filter.css
  client/src/components/SearchPage/Filter.jsx
  client/src/components/SearchPage/HomeStructureList.jsx
  client/src/main.jsx
  client/src/pages/search-page/SearchPage.css
  client/src/pages/search-page/SearchPage.jsx
  server/app/controllers/home_structureActions.js
  server/database/fixtures/HomeStructureSeeder.js
  server/database/models/HomeStructureRepository.js
Labels: REVIEW REQUESTED

#49 33 toast
  client/package.json
  client/src/App.jsx
  client/src/main.jsx
  client/src/pages/Connexion_page/ConnexionPage.jsx
  client/src/pages/profile_page/ProfilePage.jsx
  client/src/pages/search-page/SearchPage.jsx
  client/src/pages/signin/SignIn.jsx
  client/src/pages/structure_form/StructureForm.jsx
  client/src/utils/notify.js
  package-lock.json
Labels: REVIEW REQUESTED

#50 Fix sprint3
  client/index.html
  client/src/App.css
  client/src/assets/images/Btn-next.png
  client/src/assets/images/Btn-prev.png
  client/src/components/SearchPage/HomeStructureList.css
  client/src/components/nav_menu/NavMenu.css
  client/src/components/nav_menu/NavMenu.jsx
  client/src/components/search_page_components/Filter.css
  client/src/components/search_page_components/Filter.jsx
  client/src/components/search_page_components/HomeStructureList.css
  client/src/components/search_page_components/HomeStructureList.jsx
  client/src/main.jsx
  client/src/pages/Connexion_page/ConnexionPage.css
  client/src/pages/Connexion_page/ConnexionPage.jsx
  client/src/pages/home_page/homePage.css
  client/src/pages/profile_page/ProfilePage.jsx
  client/src/pages/search_page/SearchPage.css
  client/src/pages/search_page/SearchPage.jsx
  client/src/pages/signin/SignIn.jsx
  server/app/controllers/usersActions.js
Labels: REVIEW REQUESTED

#55 connexion du formaulaire à la base de données
  client/src/main.jsx
  client/src/pages/structure_form/StructureForm.jsx
  client/src/pages/structure_form/StructureForm.module.css
  server/app/controllers/home_structureActions.js
  server/database/fixtures/HomeStructureSeeder.js
  server/database/models/HomeStructureRepository.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#54 29 home structure details page
  client/src/App.css
  client/src/App.jsx
  client/src/components/home_structure_details/Reservation.css
  client/src/components/home_structure_details/Reservation.jsx
  client/src/components/profile/ProfileHeader.jsx
  client/src/components/profile/ProfileHeader.module.css
  client/src/components/profile/ProfileSection.jsx
  client/src/components/profile/ProfileSection.module.css
  client/src/components/search_page_components/filter/Filter.css
  client/src/components/search_page_components/filter/Filter.jsx
  client/src/components/search_page_components/home_strucutre_list/HomeStructureList.css
  client/src/components/search_page_components/home_strucutre_list/HomeStructureList.jsx
  client/src/components/search_page_components/is_professionnal/IsProfessionnal.css
  client/src/components/search_page_components/is_professionnal/isProfessional.jsx
  client/src/components/search_page_components/user_animal/UserAnimal.css
  client/src/components/search_page_components/user_animal/UserAnimal.jsx
  client/src/main.jsx
  client/src/pages/home_page/HomePage.jsx
  client/src/pages/home_structure_details/HomeStructureDetails.css
  client/src/pages/home_structure_details/HomeStructureDetails.jsx
  client/src/pages/profile_page/ProfilePage.jsx
  client/src/pages/search_page/SearchPage.css
  client/src/pages/search_page/SearchPage.jsx
Labels: REVIEW REQUESTED

#59 reorganize main by separating loader and action files
  client/handlers/actions/connexion_action/connexionAction.js
  client/handlers/actions/sign_in_action/signInAction.js
  client/handlers/actions/structure_form_action/structureFormAction.js
  client/handlers/loader/home_structure_loader/homeStructureLoader.js
  client/handlers/loader/profile_loader/profileLoader.js
  client/src/main.jsx
Labels: REVIEW REQUESTED

#73 35 pages in back
  client/src/components/search_page_components/filter/Filter.jsx
  client/src/pages/search_page/SearchPage.jsx
  server/app/controllers/home_structureActions.js
  server/database/fixtures/HomeStructureSeeder.js
  server/database/models/HomeStructureRepository.js
Labels: REVIEW REQUESTED

#76 37_finishing_detailshomeStructure
  client/package.json
  client/src/App.css
  client/src/components/home_structure_details/Reservation.css
  client/src/components/home_structure_details/Reservation.jsx
  client/src/components/profile/ProfileHeader.module.css
  client/src/components/search_page_components/filter/Filter.css
  client/src/pages/home_structure_details/HomeStructureDetails.css
  package-lock.json
Labels: REVIEW REQUESTED

#60 34_refactoring_db
  client/handlers/actions/sign_up_action/signUpAction.js
  client/handlers/actions/structure_form_action/structureFormAction.js
  client/src/components/search_page_components/home_strucutre_list/HomeStructureList.jsx
  client/src/main.jsx
  client/src/pages/home_page/HomePage.jsx
  client/src/pages/home_page/homePage.css
  client/src/pages/home_structure_details/HomeStructureDetails.jsx
  client/src/pages/sign_up/SignUp.jsx
  client/src/pages/sign_up/SignUp.module.css
  client/src/pages/structure_form/StructureForm.jsx
  client/src/pages/structure_form/StructureForm.module.css
  server/app/services/validateSignIn.js
  server/database/fixtures/HomeStructureSeeder.js
  server/database/fixtures/UserSeeder.js
  server/database/models/HomeStructureRepository.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#74 Middleware home structure
  server/app/routers/api/home_structure/router.js
  server/app/services/ValidateHomeStructure.js
Labels: REVIEW REQUESTED

#77 hash password
  client/src/pages/Connexion_page/ConnexionPage.jsx
  package-lock.json
  server/app/controllers/usersActions.js
  server/database/models/UsersRepository.js
  server/package.json
Labels: REVIEW REQUESTED

#79 Fix 04
  client/handlers/loader/home_structure_loader/homeStructureLoader.js
  client/index.html
  client/src/components/nav_menu/NavMenu.css
  client/src/components/nav_menu/NavMenu.jsx
  client/src/components/profile/editable_field/EditableField.jsx
  client/src/components/profile/editable_text_area/EditableTextarea.jsx
  client/src/components/profile/profile_header/ProfileHeader.jsx
  client/src/components/profile/profile_section/ProfileSection.jsx
  client/src/components/search_page_components/filter/Filter.jsx
  client/src/components/search_page_components/home_strucutre_list/HomeStructureList.jsx
  client/src/handlers/actions/connexion_action/connexionAction.js
  client/src/handlers/actions/sign_up_action/signUpAction.js
  client/src/handlers/actions/structure_form_action/structureFormAction.js
  client/src/handlers/loader/home_structure_loader/homeStructureLoader.js
  client/src/handlers/loader/profile_loader/profileLoader.js
  client/src/main.jsx
  client/src/pages/profile_page/ProfilePage.jsx
  client/src/pages/search_page/SearchPage.css
  client/src/pages/search_page/SearchPage.jsx
  client/src/pages/sign_up/SignUp.jsx
  server/app/controllers/usersActions.js
  server/app/services/ValidateHomeStructure.js
  server/app/services/ValidateLogin.js
  server/database/fixtures/HomeStructureSeeder.js
  server/database/fixtures/UserSeeder.js
  server/database/models/HomeStructureRepository.js
  server/database/models/UsersRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEW REQUESTED

#82 32 edit delete profil page
  client/src/components/home_structure_details/Reservation.css
  client/src/components/profile/editable_field/EditableField.jsx
  client/src/components/profile/editable_field/EditableField.module.css
  client/src/components/profile/editable_text_area/EditableTextarea.jsx
  client/src/components/profile/editable_text_area/EditableTextarea.module.css
  client/src/components/profile/profile_header/ProfileHeader.jsx
  client/src/components/profile/profile_header/ProfileHeader.module.css
  client/src/components/profile/profile_header/delete_profile/DeleteProfile.jsx
  client/src/components/profile/profile_header/delete_profile/DeleteProfile.module.css
  client/src/components/profile/profile_section/ProfileSection.module.css
  client/src/pages/home_structure_details/HomeStructureDetails.css
  client/src/pages/home_structure_details/HomeStructureDetails.jsx
  client/src/pages/profile_page/ProfilePage.jsx
  client/src/pages/profile_page/ProfilePage.module.css
  server/app/controllers/usersActions.js
  server/app/routers/api/users/router.js
  server/app/services/ValidateProfileEdit.js
  server/app/services/validateSignUp.js
  server/database/fixtures/HomeStructureSeeder.js
  server/database/models/HomeStructureRepository.js
  server/database/models/UsersRepository.js
Labels: REVIEW REQUESTED

#84 pages restaurées
  client/src/assets/images/dogFriends.png
  client/src/main.jsx
  client/src/pages/not_found_page/NotFoundPage.jsx
  client/src/pages/not_found_page/NotFoundPage.module.css
Labels: REVIEW REQUESTED

#86 38 middleware errors
  client/src/handlers/actions/sign_up_action/signUpAction.js
  client/src/pages/profile_page/ProfilePage.jsx
  client/src/pages/sign_up/SignUp.jsx
  server/app/routers/api/users/router.js
  server/app/services/ValidateProfileEdit.js
  server/app/services/uniqueEmailAndUsername.js
  server/app/services/validateSignUp.js
  server/app/services/validateUser.js
  server/database/models/UsersRepository.js
Labels: REVIEW REQUESTED

#89 41_add_logout_option
  client/src/components/nav_menu/NavMenu.css
  client/src/components/nav_menu/NavMenu.jsx
  server/app/controllers/usersActions.js
  server/app/routers/api/users/router.js
Labels: REVIEW REQUESTED
